exclude_patterns:
  - "examples/"
  - "*_test.go"
  - "**/*_test.go"
checks:
  nested-control-flow:
    enabled: true
    config:
      threshold: 10
  return-statements:
    enabled: true
    config:
      threshold: 10
